# Generated by Django 3.0.8 on 2021-03-09 14:45

import apps.core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id_member', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vip', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.upload_image_member)),
            ],
        ),
    ]
