# Generated by Django 3.0.8 on 2021-03-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='vip',
            field=models.IntegerField(choices=[(0, 'básico'), (1, 'premium')], default=0),
        ),
    ]
