# Generated by Django 3.0.8 on 2021-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210309_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='vip',
            field=models.CharField(choices=[('0', 'básico'), ('1', 'premium')], default='0', max_length=1),
        ),
    ]
